bases:
  - ../../application/
patches:
  - replica_count.yaml
  - resource_limit.yaml
configMapGenerator:
  - name: example-config
    namespace: example
    behavior: replace
    files:
      - configs/config.json